### PR TITLE
use the latest release of Azure Functions Core Tools

### PR DESCRIPTION
**Pull request by bmc-msft**

### CODE REVIEW

**Comment by priyaananthasankar** [comment]
@bmc-msft : Can you let us know how you are using functions core tools? Are you actually deploying functions out of cloud shell?

**Comment by bmc-msft** [comment]
Yes, I am deploying Azure Functions (among other Azure services) via cloudshell.

I'm happy to discuss my scenario privately via Microsoft's internal Teams instance.

**Comment by priyaananthasankar** [comment]
> Yes, I am deploying Azure Functions (among other Azure services) via cloudshell.
> 
> I'm happy to discuss my scenario privately via Microsoft's internal Teams instance.

Sure. ping me in Teams (Priya Ananthasankar)

**Comment by priyaananthasankar** [comment]
Started a discussion thread on the problem - as we have an opportunity to give more installation and upgrade freedom to the users of cloud shell and not carry these tools: https://github.com/Azure/CloudShell/discussions/216 - Please comment on the discussion thread and we can get back to the PR once we reach a conclusion.

**Comment by maertendMSFT** [comment]
Closing this PR as we have opened a [discussion ](https://github.com/Azure/CloudShell/discussions/216)on this topic.

We are planning on removing this package and asking folks to use NPM to install.

**Pull request closed without merging**
