### PR TITLE
install bicep CLI

### LINKED ISSUE #55: Feature: Add Bicep language CLI tool
Add bicep language CLI tool

https://github.com/Azure/bicep/blob/main/docs/installing.md

### PR DESCRIPTION
**Pull request by alex-frankel**
Closes #55

### CODE REVIEW

**Comment by edyoung** [comment]
1) I feel a little wary about including something that's labelled 'alpha'
2) Looking ahead, once you do have a stable version I think /latest link will provide the absolute latest version, even if that's not from stable release train. Not sure what your branching/release strategy will be, so this may not be an issue. 

What do you think?

**Comment by alex-frankel** [comment]
1. Fair and I think ultimately your call :) If we decide to wait, I think waiting for the 0.3 release makes sense as we will be shipping that as a "production ready" release.
2. As of now, we don't have a notion of pre-release, so whatever is in latest is the one we want everyone on. That may change as we get into more stable releases.

**Comment by alex-frankel** [comment]
Hey @edyoung - just pinging to close out this conversation. Do we want to plan to merge this PR when v0.3 is released?

**Review by swampthing1984 — COMMENTED** [review]
/

**Comment by edyoung** [comment]
Let's go with the 0.3 release.

**Review by blaquezzz — APPROVED** [review]

**Review by edyoung — APPROVED** [review]

**Comment by alex-frankel** [comment]
FYI - we are no longer in experimental mode and bicep is now production ready with our [0.3 release](https://github.com/Azure/bicep/releases/tag/v0.3.1). Can we merge this PR now?

Thanks!

**Comment by edyoung** [comment]
Sure!

**Pull request merged**
