### PR TITLE
updated kubectl install to use az aks install-cli

### PR DESCRIPTION
**Pull request by TomGeske**

### CODE REVIEW

**Comment by TomGeske** [comment]
+@weinong, @palma21 for review

**Comment by weinong** [comment]
what about Windows?

**Comment by maertendMSFT** [comment]
@weinong , not sure what you mean about windows.  This docker image is used for both the Bash and PowerShell experiences.

**Comment by palma21** [comment]
This is for cloudshell only so lgtm

(we should also consider if we don't yet, having `az acr helm install-cli` to have the latest helm

We might move this to aks install-cli eventually

**Comment by AdrianMSFT** [comment]
Hi guys, 

I have a case with _"kubectl version in cloudshell too old"_  where the customer asked how to update the kubectl version in cloud shell. I've provided him with an workaround, downloading the desired version of kubectl, then created an alias for it to set as the default one. It worked fine but as per his update  _"It is a bit difficult to spread this solution to all of our teams developing on our K8s."_ thus he asked, **Do you know if there will be a general update in cloudshell available for kubectl?** 

I addressed it internally also, but I would like to make sure I can provide a feasible statement about this query.

Thank you all!

**Comment by edyoung** [comment]
We aim to release this in our update prior to MS Ignite (9/21)

**Review by edyoung — APPROVED** [review]

**Pull request merged**
