### PR TITLE
Update ps readline and install predictors module

### PR DESCRIPTION
**Pull request by mgreenegit**

### CODE REVIEW

**Comment by naioja** [comment]
The build fails because the Maven version specified here https://github.com/Azure/CloudShell/blob/master/linux/installMaven.sh#L6 is no longer available.

The Apache.org repo replaced it with 3.8.6 whereas in the installMaven.sh it's mentioned 3.8.5.

**Comment by priyaananthasankar** [comment]
Merged a previous PR that has the Maven fix, can you update the commits?

**Comment by mgreenegit** [comment]
This branch appears to be in sync with main. Will try running the build again.

**Comment by mgreenegit** [comment]
@maertendMSFT @theJasonHelmick 
I added a new function that enables predictors and sets the style based on window size. Can you review?

You might want to manually run it in a session and make sure you like "Blue" as the foreground color.

**Comment by mgreenegit** [comment]
Ready for review

**Comment by edyoung** [comment]
Exciting!

**Comment by maertendMSFT** [comment]
We need to hold on this until we have a blog and docs ready as folks will be surprised when it shows up :)

**Comment by maertendMSFT** [comment]
@mgreenegit, can we change this PR to make this disabled by default then make a blog on how to enable it?
Then later down the line once we have more feedback we can enable this by default.

**Comment by mgreenegit** [comment]
> @mgreenegit, can we change this PR to make this disabled by default then make a blog on how to enable it? Then later down the line once we have more feedback we can enable this by default.

It installs by default and sets the style, but the "source" (which is how predictors are enabled/disabled) is not modified.

**Comment by dsajanice** [comment]
@mgreenegit we are closing this PR because we plan to pull in the latest PSReadLine module that includes the predictor by default.

**Comment by theJasonHelmick** [comment]
@mgreenegit -- we are updating PSReadLine to the new version 2.2.6 which enables predictions by default. Specifically with `History and PlugIn` enabled.  This pr will be closed when the image is updated to support predictions.

**Pull request closed without merging**
