### PR TITLE
CI: Build & Push Cloudshell Images to GHCR

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by darrentu** [comment]
@surajssd Is there a cost associated with GitHub container registry?

**Comment by surajssd** [comment]
> @surajssd Is there a cost associated with GitHub container registry?

For open source projects it is free.

**Comment by priyaananthasankar** [comment]
Please put a documentation announcement if applicable for this type of stuff. Lets kickoff a documentation change that explains which GitHub open source repo cloud shell is going into as part of release notes.

**Review by priyaananthasankar — CHANGES_REQUESTED** [review]
Please add a documentation update for this and run it through Mitchell, as I think it can be valuable.

**Comment by surajssd** [comment]
@priyaananthasankar I have added the docs, PTAL. Just note that the image won't be built until we merge the PR.

**Review by mbifeld — APPROVED** [review]
LGTM on the content side

**Review by darrentu — APPROVED** [review]

**Review by priyaananthasankar — APPROVED** [review]

**Pull request merged**
